#!/bin/sh
if [ $# -ne 0 ]
then
    sourcefiles="$*"
else
    sourcefiles="tst*.C"
fi

for file
	in ${sourcefiles}
do
	base=`basename ${file} .C`
	echo ${base}
	if make ${base}
	then
	    echo succes
	else
	    echo failure
	fi
done
