// ======================================================================
//
// Copyright (c) 1999,2000 The CGAL Consortium

// This software and related documentation are part of the Computational
// Geometry Algorithms Library (CGAL).
// This software and documentation are provided "as-is" and without warranty
// of any kind. In no event shall the CGAL Consortium be liable for any
// damage of any kind. 
//
// Every use of CGAL requires a license. 
//
// Academic research and teaching license
// - For academic research and teaching purposes, permission to use and copy
//   the software and its documentation is hereby granted free of charge,
//   provided that it is not a component of a commercial product, and this
//   notice appears in all copies of the software and related documentation. 
//
// Commercial licenses
// - A commercial license is available through Algorithmic Solutions, who also
//   markets LEDA (http://www.algorithmic-solutions.com). 
// - Commercial users may apply for an evaluation license by writing to
//   (Andreas.Fabri@geometryfactory.com). 
//
// The CGAL Consortium consists of Utrecht University (The Netherlands),
// ETH Zurich (Switzerland), Freie Universitaet Berlin (Germany),
// INRIA Sophia-Antipolis (France), Martin-Luther-University Halle-Wittenberg
// (Germany), Max-Planck-Institute Saarbrucken (Germany), RISC Linz (Austria),
// and Tel-Aviv University (Israel).
//
// ----------------------------------------------------------------------
// 
// release       : CGAL-2.3
// release_date  : 2001, August 13
// 
// file          : include/CGAL/Arithmetic_filter/static_infos/predicates/kernel_ftC2.h
// package       : Interval_arithmetic (4.114)
// author(s)     : Sylvain Pion
//
// coordinator   : INRIA Sophia-Antipolis (<Mariette.Yvinec>)
// email         : contact@cgal.org
// www           : http://www.cgal.org
//
// ======================================================================

// This file is automatically generated by
// scripts/filtered_predicates_generator.pl

#ifndef CGAL_ARITHMETIC_FILTER_PREDICATES_KERNEL_FTC2_H_STATIC_INFO_H
#define CGAL_ARITHMETIC_FILTER_PREDICATES_KERNEL_FTC2_H_STATIC_INFO_H

double Static_Filtered_equal_lineC2_6::_epsilon_0;
double Static_Filtered_equal_lineC2_6::_epsilon_1;
double Static_Filtered_equal_lineC2_6::_epsilon_2;
double Static_Filtered_equal_lineC2_6::_epsilon_3;
double Static_Filtered_equal_lineC2_6::_epsilon_4;
double Static_Filtered_equal_lineC2_6::_epsilon_5;
double Static_Filtered_equal_lineC2_6::_epsilon_6;
double Static_Filtered_equal_lineC2_6::_bound = -1.0;

unsigned Static_Filtered_equal_lineC2_6::number_of_updates = 0;

unsigned Static_Filtered_equal_lineC2_6::number_of_failures = 0;

double Static_Filtered_compare_xC2_7::_epsilon_0;
double Static_Filtered_compare_xC2_7::_epsilon_1;
double Static_Filtered_compare_xC2_7::_bound = -1.0;

unsigned Static_Filtered_compare_xC2_7::number_of_updates = 0;

unsigned Static_Filtered_compare_xC2_7::number_of_failures = 0;

double Static_Filtered_compare_xC2_9::_epsilon_0;
double Static_Filtered_compare_xC2_9::_epsilon_1;
double Static_Filtered_compare_xC2_9::_epsilon_2;
double Static_Filtered_compare_xC2_9::_epsilon_3;
double Static_Filtered_compare_xC2_9::_bound = -1.0;

unsigned Static_Filtered_compare_xC2_9::number_of_updates = 0;

unsigned Static_Filtered_compare_xC2_9::number_of_failures = 0;

double Static_Filtered_compare_xC2_12::_epsilon_0;
double Static_Filtered_compare_xC2_12::_epsilon_1;
double Static_Filtered_compare_xC2_12::_epsilon_2;
double Static_Filtered_compare_xC2_12::_bound = -1.0;

unsigned Static_Filtered_compare_xC2_12::number_of_updates = 0;

unsigned Static_Filtered_compare_xC2_12::number_of_failures = 0;

double Static_Filtered_compare_y_at_xC2_5::_epsilon_0;
double Static_Filtered_compare_y_at_xC2_5::_epsilon_1;
double Static_Filtered_compare_y_at_xC2_5::_bound = -1.0;

unsigned Static_Filtered_compare_y_at_xC2_5::number_of_updates = 0;

unsigned Static_Filtered_compare_y_at_xC2_5::number_of_failures = 0;

double Static_Filtered_compare_y_at_xC2_7::_epsilon_0;
double Static_Filtered_compare_y_at_xC2_7::_epsilon_1;
double Static_Filtered_compare_y_at_xC2_7::_epsilon_2;
double Static_Filtered_compare_y_at_xC2_7::_bound = -1.0;

unsigned Static_Filtered_compare_y_at_xC2_7::number_of_updates = 0;

unsigned Static_Filtered_compare_y_at_xC2_7::number_of_failures = 0;

double Static_Filtered_compare_y_at_xC2_9::_epsilon_0;
double Static_Filtered_compare_y_at_xC2_9::_epsilon_1;
double Static_Filtered_compare_y_at_xC2_9::_epsilon_2;
double Static_Filtered_compare_y_at_xC2_9::_bound = -1.0;

unsigned Static_Filtered_compare_y_at_xC2_9::number_of_updates = 0;

unsigned Static_Filtered_compare_y_at_xC2_9::number_of_failures = 0;

double Static_Filtered_compare_y_at_xC2_12::_epsilon_0;
double Static_Filtered_compare_y_at_xC2_12::_epsilon_1;
double Static_Filtered_compare_y_at_xC2_12::_epsilon_2;
double Static_Filtered_compare_y_at_xC2_12::_epsilon_3;
double Static_Filtered_compare_y_at_xC2_12::_bound = -1.0;

unsigned Static_Filtered_compare_y_at_xC2_12::number_of_updates = 0;

unsigned Static_Filtered_compare_y_at_xC2_12::number_of_failures = 0;

double Static_Filtered_equal_directionC2_4::_epsilon_0;
double Static_Filtered_equal_directionC2_4::_epsilon_1;
double Static_Filtered_equal_directionC2_4::_epsilon_2;
double Static_Filtered_equal_directionC2_4::_epsilon_3;
double Static_Filtered_equal_directionC2_4::_epsilon_4;
double Static_Filtered_equal_directionC2_4::_bound = -1.0;

unsigned Static_Filtered_equal_directionC2_4::number_of_updates = 0;

unsigned Static_Filtered_equal_directionC2_4::number_of_failures = 0;

double Static_Filtered_compare_deltax_deltayC2_4::_epsilon_0;
double Static_Filtered_compare_deltax_deltayC2_4::_bound = -1.0;

unsigned Static_Filtered_compare_deltax_deltayC2_4::number_of_updates = 0;

unsigned Static_Filtered_compare_deltax_deltayC2_4::number_of_failures = 0;

double Static_Filtered_orientationC2_6::_epsilon_0;
double Static_Filtered_orientationC2_6::_bound = -1.0;

unsigned Static_Filtered_orientationC2_6::number_of_updates = 0;

unsigned Static_Filtered_orientationC2_6::number_of_failures = 0;

double Static_Filtered_angleC2_6::_epsilon_0;
double Static_Filtered_angleC2_6::_bound = -1.0;

unsigned Static_Filtered_angleC2_6::number_of_updates = 0;

unsigned Static_Filtered_angleC2_6::number_of_failures = 0;

double Static_Filtered_side_of_oriented_circleC2_8::_epsilon_0;
double Static_Filtered_side_of_oriented_circleC2_8::_bound = -1.0;

unsigned Static_Filtered_side_of_oriented_circleC2_8::number_of_updates = 0;

unsigned Static_Filtered_side_of_oriented_circleC2_8::number_of_failures = 0;

double Static_Filtered_side_of_bounded_circleC2_8::_epsilon_0;
double Static_Filtered_side_of_bounded_circleC2_8::_epsilon_1;
double Static_Filtered_side_of_bounded_circleC2_8::_bound = -1.0;

unsigned Static_Filtered_side_of_bounded_circleC2_8::number_of_updates = 0;

unsigned Static_Filtered_side_of_bounded_circleC2_8::number_of_failures = 0;

double Static_Filtered_side_of_bounded_circleC2_6::_epsilon_0;
double Static_Filtered_side_of_bounded_circleC2_6::_bound = -1.0;

unsigned Static_Filtered_side_of_bounded_circleC2_6::number_of_updates = 0;

unsigned Static_Filtered_side_of_bounded_circleC2_6::number_of_failures = 0;

double Static_Filtered_cmp_dist_to_pointC2_6::_epsilon_0;
double Static_Filtered_cmp_dist_to_pointC2_6::_bound = -1.0;

unsigned Static_Filtered_cmp_dist_to_pointC2_6::number_of_updates = 0;

unsigned Static_Filtered_cmp_dist_to_pointC2_6::number_of_failures = 0;

double Static_Filtered_cmp_signed_dist_to_directionC2_6::_epsilon_0;
double Static_Filtered_cmp_signed_dist_to_directionC2_6::_bound = -1.0;

unsigned Static_Filtered_cmp_signed_dist_to_directionC2_6::number_of_updates = 0;

unsigned Static_Filtered_cmp_signed_dist_to_directionC2_6::number_of_failures = 0;

double Static_Filtered_cmp_signed_dist_to_lineC2_8::_epsilon_0;
double Static_Filtered_cmp_signed_dist_to_lineC2_8::_bound = -1.0;

unsigned Static_Filtered_cmp_signed_dist_to_lineC2_8::number_of_updates = 0;

unsigned Static_Filtered_cmp_signed_dist_to_lineC2_8::number_of_failures = 0;

double Static_Filtered_side_of_oriented_lineC2_5::_epsilon_0;
double Static_Filtered_side_of_oriented_lineC2_5::_bound = -1.0;

unsigned Static_Filtered_side_of_oriented_lineC2_5::number_of_updates = 0;

unsigned Static_Filtered_side_of_oriented_lineC2_5::number_of_failures = 0;

#endif // CGAL_ARITHMETIC_FILTER_PREDICATES_KERNEL_FTC2_H_STATIC_INFO_H
