// ======================================================================
//
// Copyright (c) 1999 The CGAL Consortium

// This software and related documentation is part of the Computational
// Geometry Algorithms Library (CGAL).
// This software and documentation is provided "as-is" and without warranty
// of any kind. In no event shall the CGAL Consortium be liable for any
// damage of any kind. 
//
// Every use of CGAL requires a license. 
//
// Academic research and teaching license
// - For academic research and teaching purposes, permission to use and copy
//   the software and its documentation is hereby granted free of charge,
//   provided that it is not a component of a commercial product, and this
//   notice appears in all copies of the software and related documentation. 
//
// Commercial licenses
// - A commercial license is available through Algorithmic Solutions, who also
//   markets LEDA (http://www.algorithmic-solutions.de). 
// - Commercial users may apply for an evaluation license by writing to
//   Algorithmic Solutions (contact@algorithmic-solutions.com). 
//
// The CGAL Consortium consists of Utrecht University (The Netherlands),
// ETH Zurich (Switzerland), Free University of Berlin (Germany),
// INRIA Sophia-Antipolis (France), Martin-Luther-University Halle-Wittenberg
// (Germany), Max-Planck-Institute Saarbrucken (Germany), RISC Linz (Austria),
// and Tel-Aviv University (Israel).
//
// ----------------------------------------------------------------------
// 
// release       : CGAL-2.1
// release_date  : 2000, January 11
// 
// file          : include/CGAL/Arithmetic_filter/static_infos/predicates/kernel_ftC3.h
// package       : Interval_arithmetic (4.39)
// author(s)     : Sylvain Pion
//
// coordinator   : INRIA Sophia-Antipolis (<Mariette.Yvinec>)
// email         : cgal@cs.uu.nl
//
// ======================================================================

// This file is automatically generated by
// scripts/filtered_predicates_generator.pl

#ifndef CGAL_ARITHMETIC_FILTER_PREDICATES_KERNEL_FTC3_H_STATIC_INFO_H
#define CGAL_ARITHMETIC_FILTER_PREDICATES_KERNEL_FTC3_H_STATIC_INFO_H

double Static_Filtered_collinearC3_9::_epsilon_0;
double Static_Filtered_collinearC3_9::_epsilon_1;
double Static_Filtered_collinearC3_9::_epsilon_2;
double Static_Filtered_collinearC3_9::_bound = -1.0;

unsigned Static_Filtered_collinearC3_9::number_of_updates = 0;

unsigned Static_Filtered_collinearC3_9::number_of_failures = 0;

double Static_Filtered_orientationC3_12::_epsilon_0;
double Static_Filtered_orientationC3_12::_bound = -1.0;

unsigned Static_Filtered_orientationC3_12::number_of_updates = 0;

unsigned Static_Filtered_orientationC3_12::number_of_failures = 0;

double Static_Filtered_equal_directionC3_6::_epsilon_0;
double Static_Filtered_equal_directionC3_6::_epsilon_1;
double Static_Filtered_equal_directionC3_6::_epsilon_2;
double Static_Filtered_equal_directionC3_6::_epsilon_3;
double Static_Filtered_equal_directionC3_6::_epsilon_4;
double Static_Filtered_equal_directionC3_6::_epsilon_5;
double Static_Filtered_equal_directionC3_6::_epsilon_6;
double Static_Filtered_equal_directionC3_6::_epsilon_7;
double Static_Filtered_equal_directionC3_6::_epsilon_8;
double Static_Filtered_equal_directionC3_6::_bound = -1.0;

unsigned Static_Filtered_equal_directionC3_6::number_of_updates = 0;

unsigned Static_Filtered_equal_directionC3_6::number_of_failures = 0;

double Static_Filtered_side_of_oriented_planeC3_7::_epsilon_0;
double Static_Filtered_side_of_oriented_planeC3_7::_bound = -1.0;

unsigned Static_Filtered_side_of_oriented_planeC3_7::number_of_updates = 0;

unsigned Static_Filtered_side_of_oriented_planeC3_7::number_of_failures = 0;

double Static_Filtered_side_of_oriented_sphereC3_15::_epsilon_0;
double Static_Filtered_side_of_oriented_sphereC3_15::_bound = -1.0;

unsigned Static_Filtered_side_of_oriented_sphereC3_15::number_of_updates = 0;

unsigned Static_Filtered_side_of_oriented_sphereC3_15::number_of_failures = 0;

double Static_Filtered_side_of_bounded_sphereC3_15::_epsilon_0;
double Static_Filtered_side_of_bounded_sphereC3_15::_epsilon_1;
double Static_Filtered_side_of_bounded_sphereC3_15::_bound = -1.0;

unsigned Static_Filtered_side_of_bounded_sphereC3_15::number_of_updates = 0;

unsigned Static_Filtered_side_of_bounded_sphereC3_15::number_of_failures = 0;

double Static_Filtered_cmp_dist_to_pointC3_9::_epsilon_0;
double Static_Filtered_cmp_dist_to_pointC3_9::_bound = -1.0;

unsigned Static_Filtered_cmp_dist_to_pointC3_9::number_of_updates = 0;

unsigned Static_Filtered_cmp_dist_to_pointC3_9::number_of_failures = 0;

double Static_Filtered_cmp_signed_dist_to_directionC3_9::_epsilon_0;
double Static_Filtered_cmp_signed_dist_to_directionC3_9::_bound = -1.0;

unsigned Static_Filtered_cmp_signed_dist_to_directionC3_9::number_of_updates = 0;

unsigned Static_Filtered_cmp_signed_dist_to_directionC3_9::number_of_failures = 0;

double Static_Filtered_cmp_signed_dist_to_planeC3_15::_epsilon_0;
double Static_Filtered_cmp_signed_dist_to_planeC3_15::_bound = -1.0;

unsigned Static_Filtered_cmp_signed_dist_to_planeC3_15::number_of_updates = 0;

unsigned Static_Filtered_cmp_signed_dist_to_planeC3_15::number_of_failures = 0;

#endif // CGAL_ARITHMETIC_FILTER_PREDICATES_KERNEL_FTC3_H_STATIC_INFO_H
