// ======================================================================
//
// Copyright (c) 1999,2000 The CGAL Consortium

// This software and related documentation are part of the Computational
// Geometry Algorithms Library (CGAL).
// This software and documentation are provided "as-is" and without warranty
// of any kind. In no event shall the CGAL Consortium be liable for any
// damage of any kind. 
//
// Every use of CGAL requires a license. 
//
// Academic research and teaching license
// - For academic research and teaching purposes, permission to use and copy
//   the software and its documentation is hereby granted free of charge,
//   provided that it is not a component of a commercial product, and this
//   notice appears in all copies of the software and related documentation. 
//
// Commercial licenses
// - A commercial license is available through Algorithmic Solutions, who also
//   markets LEDA (http://www.algorithmic-solutions.com). 
// - Commercial users may apply for an evaluation license by writing to
//   (Andreas.Fabri@geometryfactory.com). 
//
// The CGAL Consortium consists of Utrecht University (The Netherlands),
// ETH Zurich (Switzerland), Freie Universitaet Berlin (Germany),
// INRIA Sophia-Antipolis (France), Martin-Luther-University Halle-Wittenberg
// (Germany), Max-Planck-Institute Saarbrucken (Germany), RISC Linz (Austria),
// and Tel-Aviv University (Israel).
//
// ----------------------------------------------------------------------
// 
// release       : CGAL-2.3
// release_date  : 2001, August 13
// 
// file          : include/CGAL/Arithmetic_filter/static_infos/predicates/Regular_triangulation_ftC2.h
// package       : Interval_arithmetic (4.114)
// author(s)     : Sylvain Pion
//
// coordinator   : INRIA Sophia-Antipolis (<Mariette.Yvinec>)
// email         : contact@cgal.org
// www           : http://www.cgal.org
//
// ======================================================================

// This file is automatically generated by
// scripts/filtered_predicates_generator.pl

#ifndef CGAL_ARITHMETIC_FILTER_REGULAR_TRIANGULATION_FTC2_H_STATIC_INFO_H
#define CGAL_ARITHMETIC_FILTER_REGULAR_TRIANGULATION_FTC2_H_STATIC_INFO_H

double Static_Filtered_power_testC2_12::_epsilon_0;
double Static_Filtered_power_testC2_12::_bound = -1.0;

unsigned Static_Filtered_power_testC2_12::number_of_updates = 0;

unsigned Static_Filtered_power_testC2_12::number_of_failures = 0;

double Static_Filtered_power_testC2_9::_epsilon_0;
double Static_Filtered_power_testC2_9::_epsilon_1;
double Static_Filtered_power_testC2_9::_epsilon_2;
double Static_Filtered_power_testC2_9::_epsilon_3;
double Static_Filtered_power_testC2_9::_bound = -1.0;

unsigned Static_Filtered_power_testC2_9::number_of_updates = 0;

unsigned Static_Filtered_power_testC2_9::number_of_failures = 0;

#endif // CGAL_ARITHMETIC_FILTER_REGULAR_TRIANGULATION_FTC2_H_STATIC_INFO_H
